spring.application.name=taco-cloud1
server.port=9090
taco.orders.pageSize = 10
# URL ??? ??????????? ? ????? ???? ?????? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.data.rest.base-path = /api
# ??????? ??? ???????????? ? ?????? ??? ???????????
spring.datasource.username=postgres
spring.datasource.password=postgres

# ??????? ??????? ???? ??????
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????????????? ????????? (?? ???????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

github.client.clientId=[CLIENT_ID]
github.client.clientSecret=[CLIENT_SECRET]
github.client.userAuthorizationUri=https://github.com/login/oauth/authorize
github.client.accessTokenUri=https://github.com/login/oauth/access_token
github.client.clientAuthenticationScheme=form
github.resource.userInfoUri=https://api.github.com/user
github.resource.repoUri=https://api.github.com/user/repos

spring.security.oauth2.client.registration.google.client-id=<your-google-client-id>
spring.security.oauth2.client.registration.google.client-secret=<your-google-client-secret>

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.file-date-format=yyyy-MM-dd
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log